extend_path;

prwaitbar off
prwarning off

digits = 0:9;
ndigits = length(digits);
train_fraction = 0.2;
side = 16;

images = prnist(digits, 1:1000);
[ train_images ...
, test_images ...
, train_indices ...
, test_indices] = gendat(images, train_fraction);

mappings = {
    ; 'speckle < 20, ecc > .85, rot < 30', im_filter_speckles(20)*im_rot_norm(.85, 30)*im_box(0) ...
    ; 'speckle < 20, ecc > .90, rot < 30', im_filter_speckles(20)*im_rot_norm(.90, 30)*im_box(0) ...
    ; 'speckle < 20, ecc > .95, rot < 30', im_filter_speckles(20)*im_rot_norm(.95, 30)*im_box(0) ...
    ...
    ; 'speckle < 20, ecc > .85, rot < 40', im_filter_speckles(20)*im_rot_norm(.85, 40)*im_box(0) ...
    ; 'speckle < 20, ecc > .90, rot < 40', im_filter_speckles(20)*im_rot_norm(.90, 40)*im_box(0) ...
    ; 'speckle < 20, ecc > .95, rot < 40', im_filter_speckles(20)*im_rot_norm(.95, 40)*im_box(0) ...
    ...
    ; 'speckle < 20, ecc > .85, rot < 50', im_filter_speckles(20)*im_rot_norm(.85, 50)*im_box(0) ...
    ; 'speckle < 20, ecc > .90, rot < 50', im_filter_speckles(20)*im_rot_norm(.90, 50)*im_box(0) ...
    ; 'speckle < 20, ecc > .95, rot < 50', im_filter_speckles(20)*im_rot_norm(.95, 50)*im_box(0) ...
    ...
    ; 'speckle < 40, ecc > .85, rot < 30', im_filter_speckles(40)*im_rot_norm(.85, 30)*im_box(0) ...
    ; 'speckle < 40, ecc > .90, rot < 30', im_filter_speckles(40)*im_rot_norm(.90, 30)*im_box(0) ...
    ; 'speckle < 40, ecc > .95, rot < 30', im_filter_speckles(40)*im_rot_norm(.95, 30)*im_box(0) ...
    ...
    ; 'speckle < 40, ecc > .85, rot < 40', im_filter_speckles(40)*im_rot_norm(.85, 40)*im_box(0) ...
    ; 'speckle < 40, ecc > .90, rot < 40', im_filter_speckles(40)*im_rot_norm(.90, 40)*im_box(0) ...
    ; 'speckle < 40, ecc > .95, rot < 40', im_filter_speckles(40)*im_rot_norm(.95, 40)*im_box(0) ...
    ...
    ; 'speckle < 40, ecc > .85, rot < 50', im_filter_speckles(40)*im_rot_norm(.85, 50)*im_box(0) ...
    ; 'speckle < 40, ecc > .90, rot < 50', im_filter_speckles(40)*im_rot_norm(.90, 50)*im_box(0) ...
    ; 'speckle < 40, ecc > .95, rot < 50', im_filter_speckles(40)*im_rot_norm(.95, 50)*im_box(0) ...
};
nmappings = length(mappings);

errors = zeros(nmappings, 1);
for i = 1:nmappings
    a = prdataset(im_resize(train_images * mappings{i, 2}, [side, side], 'bicubic'));
    t = prdataset(im_resize(test_images * mappings{i, 2}, [side, side], 'bicubic'));
    w = pcam([], .9)*parzenc;
    errors(i) = testc(t, a*w);
    fprintf('%d/%d error: %f\n', i, nmappings, errors(i));
end

a = prdataset(im_fill_norm(im_filter_speckles(20)*train_images, side, 0));
t = prdataset(im_fill_norm(im_filter_speckles(20)*test_images, side, 0));
w = pcam([], .9)*parzenc;
identityError20 = testc(t, a*w)

a = prdataset(im_fill_norm(im_filter_speckles(40)*train_images, side, 0));
t = prdataset(im_fill_norm(im_filter_speckles(40)*test_images, side, 0));
w = pcam([], .9)*parzenc;
identityError40 = testc(t, a*w)

[bestError, bestIndex] = min(errors)
bestTitle = mappings{bestIndex, 1}
errorsEccRot = reshape(errors, 4, 4)

errorsImg = (errorsEccRot - min(errors))./(max(errors) - min(errors));
imshow(imresize(errorsImg, 40, 'box'));

imwrite(imresize(errorsImg, 20, 'box'), 'preprocessing_optimize_speckle_rotation.png');



