% preprocess_rot_stretch
% for use with nist_eval
function a = preprocess_rot_stretch(images)
    images = images ...
        * im_filter_speckles(4) ...
        * im_rot_norm ...
        * im_box(1) ...
        * im_gauss(1);

    a = prdataset(im_resize(images, [13 13], 'bicubic'));
end

