extend_path;

prwaitbar off
prwarning off

digits = 0:9;
ndigits = length(digits);
train_fraction = 0.2;
side = 16;

images = prnist(digits, 1:1000);
[ train_images ...
, test_images ...
, train_indices ...
, test_indices] = gendat(images, train_fraction);

mappings = { ...
    ; 'min ecc .6, max rot = 30', im_rot_norm(.6, 30)*im_box(0) ...
    ; 'min ecc .7, max rot = 30', im_rot_norm(.7, 30)*im_box(0) ...
    ; 'min ecc .8, max rot = 30', im_rot_norm(.8, 30)*im_box(0) ...
    ; 'min ecc .9, max rot = 30', im_rot_norm(.9, 30)*im_box(0) ...
    ...
    ; 'min ecc .6, max rot = 40', im_rot_norm(.6, 40)*im_box(0) ...
    ; 'min ecc .7, max rot = 40', im_rot_norm(.7, 40)*im_box(0) ...
    ; 'min ecc .8, max rot = 40', im_rot_norm(.8, 40)*im_box(0) ...
    ; 'min ecc .9, max rot = 40', im_rot_norm(.9, 40)*im_box(0) ...
    ...
    ; 'min ecc .6, max rot = 50', im_rot_norm(.6, 50)*im_box(0) ...
    ; 'min ecc .7, max rot = 50', im_rot_norm(.7, 50)*im_box(0) ...
    ; 'min ecc .8, max rot = 50', im_rot_norm(.8, 50)*im_box(0) ...
    ; 'min ecc .9, max rot = 50', im_rot_norm(.9, 50)*im_box(0) ...
    ...
    ; 'min ecc .6, max rot = 60', im_rot_norm(.6, 60)*im_box(0) ...
    ; 'min ecc .7, max rot = 60', im_rot_norm(.7, 60)*im_box(0) ...
    ; 'min ecc .8, max rot = 60', im_rot_norm(.8, 60)*im_box(0) ...
    ; 'min ecc .9, max rot = 60', im_rot_norm(.9, 60)*im_box(0) ...
};
nmappings = length(mappings);

errors = zeros(nmappings, 1);
for i = 1:nmappings
    a = prdataset(im_resize(train_images * mappings{i, 2}, [side, side], 'bicubic'));
    t = prdataset(im_resize(test_images * mappings{i, 2}, [side, side], 'bicubic'));
    w = pcam([], .9)*parzenc;
    errors(i) = testc(t, a*w);
    errors(i)
end

a = prdataset(im_fill_norm(train_images, side, 0));
t = prdataset(im_fill_norm(test_images, side, 0));
w = pcam([], .9)*parzenc;
identityError = testc(t, a*w)

[bestError, bestIndex] = min(errors)
bestTitle = mappings{bestIndex, 1}
errorsEccRot = reshape(errors, 4, 4)

errorsImg = (errorsEccRot - min(errors))./(max(errors) - min(errors));
imshow(imresize(errorsImg, 20, 'box'));

imwrite(imresize(errorsImg, 20, 'box'), 'preprocessing_optimize_rotation.png');



