extend_path

digits = 0:9;
images = prnist(digits, 1:200);

preprocessing_functions = { ...
    'preprocess_speckle_gauss0_fill', ...
    'preprocess_speckle_gauss0_stretch', ...
    'preprocess_speckle_gauss1_fill', ...
    'preprocess_speckle_gauss2_fill', ...
    'preprocess_speckle_gauss4_fill', ...
    'preprocess_speckle_rot_box0_gauss0_stretch', ...
    'preprocess_speckle_rot_box0_gauss1_stretch', ...
    'preprocess_speckle_rot_box0_gauss2_stretch', ...
    'preprocess_speckle_rot_box0_gauss4_stretch' ...
};

for cname = preprocessing_functions
    name = cname{1};
    func = str2func(name);
    a = func(images);
    w = ldc(a);
    data = +w;
    digit_images = []; % mean digit images
    for i = (digits + 1)
        digit_image = reshape(data.mean(i,:), 16, 16);
        digit_images = [ digit_images, digit_image ];
    end
    imwrite(imresize(digit_images, 8, 'box'), strcat(name, '.png'));
end